"use server"; import { revalidatePath } from "next/cache"; import { z } from "zod"; import { auth } from "@/auth"; import { db } from "@/lib/db";
const projectSchema=z.object({title:z.string().min(3).max(120),slug:z.string().regex(/^[a-z0-9-]+$/),category:z.string().min(2),description:z.string().min(10).max(500),content:z.string().min(10),technologies:z.string(),githubUrl:z.string().optional(),liveUrl:z.string().optional(),featured:z.boolean(),published:z.boolean()});
async function secure(){if(!(await auth())?.user)throw new Error("Unauthorized")}
export async function saveProject(form:FormData){await secure();const raw={...Object.fromEntries(form),featured:form.get("featured")==="on",published:form.get("published")==="on"};const p=projectSchema.safeParse(raw);if(!p.success)throw new Error("Invalid project data");const {technologies,...data}=p.data;await db.project.upsert({where:{slug:data.slug},update:{...data,githubUrl:data.githubUrl||null,liveUrl:data.liveUrl||null,technologies:technologies.split(",").map(x=>x.trim()).filter(Boolean)},create:{...data,githubUrl:data.githubUrl||null,liveUrl:data.liveUrl||null,technologies:technologies.split(",").map(x=>x.trim()).filter(Boolean),images:[]}});revalidatePath("/admin/projects");revalidatePath("/projects")}
export async function deleteProject(form:FormData){await secure();const id=z.string().cuid().parse(form.get("id"));await db.project.delete({where:{id}});revalidatePath("/admin/projects")}
export async function updateMessage(form:FormData){await secure();const id=z.string().cuid().parse(form.get("id"));const status=z.enum(["UNREAD","READ","REPLIED"]).parse(form.get("status"));await db.contactMessage.update({where:{id},data:{status}});revalidatePath("/admin/messages")}
export async function saveSkill(form:FormData){await secure();const data=z.object({name:z.string().min(2),category:z.string().min(2),level:z.enum(["Learning","Comfortable","Advanced"]),icon:z.string().optional()}).parse(Object.fromEntries(form));await db.skill.upsert({where:{name_category:{name:data.name,category:data.category}},update:data,create:data});revalidatePath("/admin/skills")}
export async function saveExperience(form:FormData){await secure();const p=z.object({position:z.string().min(2),company:z.string().min(2),location:z.string().optional(),startDate:z.coerce.date(),endDate:z.string().optional(),description:z.string().min(10),technologies:z.string()}).parse(Object.fromEntries(form));await db.experience.create({data:{...p,endDate:p.endDate?new Date(p.endDate):null,current:!p.endDate,technologies:p.technologies.split(",").map(x=>x.trim()),responsibilities:[]}});revalidatePath("/admin/experience")}
export async function saveCertificate(form:FormData){await secure();const p=z.object({name:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/),issuer:z.string().min(2),issueDate:z.coerce.date(),credentialUrl:z.string().optional(),skills:z.string()}).parse(Object.fromEntries(form));const {skills,...data}=p;const values=skills.split(",").map(x=>x.trim()).filter(Boolean);await db.certificate.upsert({where:{slug:data.slug},update:{...data,credentialUrl:data.credentialUrl||null,skills:values},create:{...data,credentialUrl:data.credentialUrl||null,skills:values}});revalidatePath("/admin/certificates")}
export async function savePost(form:FormData){await secure();const p=z.object({title:z.string().min(3),slug:z.string().regex(/^[a-z0-9-]+$/),excerpt:z.string().min(10),content:z.string().min(10),category:z.string().min(2),tags:z.string(),seoTitle:z.string().optional(),seoDescription:z.string().optional(),status:z.enum(["DRAFT","PUBLISHED"])}).parse(Object.fromEntries(form));const {tags,...data}=p;await db.blogPost.upsert({where:{slug:data.slug},update:{...data,tags:tags.split(",").map(x=>x.trim()),publishedAt:data.status==="PUBLISHED"?new Date():null},create:{...data,tags:tags.split(",").map(x=>x.trim()),publishedAt:data.status==="PUBLISHED"?new Date():null}});revalidatePath("/admin/blog");revalidatePath("/blog")}
export async function saveSettings(form:FormData){await secure();const data=z.object({name:z.string().min(2),role:z.string().min(2),bio:z.string().min(10),email:z.email(),location:z.string().min(2),github:z.string().optional(),linkedin:z.string().optional(),instagram:z.string().optional(),cvUrl:z.string().optional(),seoTitle:z.string().optional(),seoDescription:z.string().optional()}).parse(Object.fromEntries(form));await db.siteSetting.upsert({where:{id:"site"},update:data,create:{id:"site",...data}});revalidatePath("/")}
export async function deleteContent(form:FormData){await secure();const id=z.string().cuid().parse(form.get("id"));const model=z.enum(["skill","experience","certificate","blogPost"]).parse(form.get("model"));if(model==="skill")await db.skill.delete({where:{id}});else if(model==="experience")await db.experience.delete({where:{id}});else if(model==="certificate")await db.certificate.delete({where:{id}});else await db.blogPost.delete({where:{id}});revalidatePath(`/admin/${model==="blogPost"?"blog":model+"s"}`)}
